version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  io_service:
    build: ./io/
    restart: always
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    ports:
      - "5050:80" # Change 5050 to any desired port number

  flask_service:
    build: ./backend/
    restart: always
    depends_on:
      - io_service
    ports:
      - "5000:80" # Change 5000 to any desired port number

  auth:
    build: ./auth/
    restart: always
    depends_on:
      - io_service
    ports:
      - "5001:80" # Change 5000 to any desired port number

volumes:
  data:
