{
 "title": "Reservations Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Users busy on date",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    u.username,\r\n    '2024-05-13' AS reservation_date,\r\n    CASE WHEN r.reservation_id IS NOT NULL THEN 0 ELSE 1 END AS busy_on_day\r\nFROM \r\n    Users u\r\nLEFT JOIN \r\n    Reservations r ON u.user_id = r.user_id AND r.reservation_date = '2024-05-13'\r\nORDER BY \r\n    u.username;\r\n"
    }
   ]
  },
  {
   "title": "Reservations",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT workspace_id, user_id, reservation_date, start_time, end_time FROM (SELECT * FROM reservations ORDER BY reservation_date, start_time, end_time); "
    }
   ]
  }
 ]
}
{
 "title": "Users overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Registered and Logged In Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('minute', created_at) AS minute,\r\n    SUM(COUNT(*)) OVER (ORDER BY DATE_TRUNC('minute', created_at)) AS registered_users,\r\n    SUM(COUNT(token)) OVER (ORDER BY DATE_TRUNC('minute', created_at)) AS logged_in_users\r\nFROM Users\r\nGROUP BY DATE_TRUNC('minute', created_at)\r\nORDER BY minute;\r\n"
    }
   ]
  },
  {
   "title": "Users Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "rawSql": "SELECT * FROM users  " }
   ]
  }
 ]
}
{
 "title": "Workspaces Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All Workspaces",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT workspace_name, capacity, location, description\r\nFROM Workspaces\r\nGROUP BY location, description, workspace_name, capacity\r\nORDER BY location, description, capacity;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capacity of every workspace",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT workspace_name, capacity\r\nFROM Workspaces\r\nORDER BY capacity;\r\n"
    }
   ]
  }
 ]
}