name: Docker Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Build and Push
        env:
          CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
          CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
        run: |
          docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
          docker build --pull -t stefanjumarea/idp-kong -f kong/Dockerfile kong
          docker push stefanjumarea/idp-kong

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Deploy Service
        run: |
          curl -k -XPOST https://ip172-18-0-77-cov4fv0l2o90008hoh30-9443.direct.labs.play-with-docker.com/api/webhooks/a3f1dd34-ec69-40a4-a558-f56042dbb022
