apiVersion: 1

datasources:
  - name: Postgres
    isDefault: true
    type: postgres
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: "postgres"
    jsonData:
      database: database
      sslmode: "disable" # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1000
      timescaledb: false